CREATE DATABASE javaee DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE  noms (
 id INT( 11 ) NOT NULL AUTO_INCREMENT ,
 nom VARCHAR( 200 ) NOT NULL ,
 prenom VARCHAR( 200 ) NOT NULL ,
 PRIMARY KEY ( id )
) ENGINE = INNODB;